CREATE DATABASE IF NOT EXISTS mysns
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE mysns;

CREATE TABLE IF NOT EXISTS user(
	id VARCHAR(128) PRIMARY KEY, -- "email"
	password VARCHAR(32),
	name VARCHAR(32),
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS feed(
	no INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	id VARCHAR(128), -- "email"
	content VARCHAR(4096),
	images VARCHAR(1024), -- "url"
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mysns`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(4500) NULL,
  `star` INT NULL,
  `author` VARCHAR(45) NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS list(
	userId VARCHAR(10) PRIMARY KEY,
	password VARCHAR(20),
	passwordCheck VARCHAR(20),
	name VARCHAR(12)
);

CREATE TABLE IF NOT EXISTS feed(
	class VARCHAR(20) PRIMARY KEY,
	title VARCHAR(128),
	images VARCHAR(1024),
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS addclass(
	lecture VARCHAR(20) PRIMARY KEY,
	book VARCHAR(128),
	estimate VARCHAR(12), 
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);